package entidad;
// Generated 15-feb-2016 18:48:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GnrPost generated by hbm2java
 */
public class GnrPost  implements java.io.Serializable {


     private Integer postId;
     private String postTitle;
     private String postSlug;
     private String postAbstract;
     private String postBody;
     private Date postDate;
     private String postAuthor;
     private String postVisible;
     private String postImage;
     private int postCategoryId;
     private String postTagId;
     private int postLangId;
     private int postCountryId;
     private String postHeaderTitle;
     private String postHeaderKeywords;
     private String postHeaderDescription;
     private String postHeaderAuthor;
     private String postFolder;

    public GnrPost() {
    }

    public GnrPost(String postTitle, String postSlug, String postAbstract, String postBody, Date postDate, String postAuthor, String postVisible, String postImage, int postCategoryId, String postTagId, int postLangId, int postCountryId, String postHeaderTitle, String postHeaderKeywords, String postHeaderDescription, String postHeaderAuthor, String postFolder) {
       this.postTitle = postTitle;
       this.postSlug = postSlug;
       this.postAbstract = postAbstract;
       this.postBody = postBody;
       this.postDate = postDate;
       this.postAuthor = postAuthor;
       this.postVisible = postVisible;
       this.postImage = postImage;
       this.postCategoryId = postCategoryId;
       this.postTagId = postTagId;
       this.postLangId = postLangId;
       this.postCountryId = postCountryId;
       this.postHeaderTitle = postHeaderTitle;
       this.postHeaderKeywords = postHeaderKeywords;
       this.postHeaderDescription = postHeaderDescription;
       this.postHeaderAuthor = postHeaderAuthor;
       this.postFolder = postFolder;
    }
   
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }
    public String getPostTitle() {
        return this.postTitle;
    }
    
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle;
    }
    public String getPostSlug() {
        return this.postSlug;
    }
    
    public void setPostSlug(String postSlug) {
        this.postSlug = postSlug;
    }
    public String getPostAbstract() {
        return this.postAbstract;
    }
    
    public void setPostAbstract(String postAbstract) {
        this.postAbstract = postAbstract;
    }
    public String getPostBody() {
        return this.postBody;
    }
    
    public void setPostBody(String postBody) {
        this.postBody = postBody;
    }
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
    public String getPostAuthor() {
        return this.postAuthor;
    }
    
    public void setPostAuthor(String postAuthor) {
        this.postAuthor = postAuthor;
    }
    public String getPostVisible() {
        return this.postVisible;
    }
    
    public void setPostVisible(String postVisible) {
        this.postVisible = postVisible;
    }
    public String getPostImage() {
        return this.postImage;
    }
    
    public void setPostImage(String postImage) {
        this.postImage = postImage;
    }
    public int getPostCategoryId() {
        return this.postCategoryId;
    }
    
    public void setPostCategoryId(int postCategoryId) {
        this.postCategoryId = postCategoryId;
    }
    public String getPostTagId() {
        return this.postTagId;
    }
    
    public void setPostTagId(String postTagId) {
        this.postTagId = postTagId;
    }
    public int getPostLangId() {
        return this.postLangId;
    }
    
    public void setPostLangId(int postLangId) {
        this.postLangId = postLangId;
    }
    public int getPostCountryId() {
        return this.postCountryId;
    }
    
    public void setPostCountryId(int postCountryId) {
        this.postCountryId = postCountryId;
    }
    public String getPostHeaderTitle() {
        return this.postHeaderTitle;
    }
    
    public void setPostHeaderTitle(String postHeaderTitle) {
        this.postHeaderTitle = postHeaderTitle;
    }
    public String getPostHeaderKeywords() {
        return this.postHeaderKeywords;
    }
    
    public void setPostHeaderKeywords(String postHeaderKeywords) {
        this.postHeaderKeywords = postHeaderKeywords;
    }
    public String getPostHeaderDescription() {
        return this.postHeaderDescription;
    }
    
    public void setPostHeaderDescription(String postHeaderDescription) {
        this.postHeaderDescription = postHeaderDescription;
    }
    public String getPostHeaderAuthor() {
        return this.postHeaderAuthor;
    }
    
    public void setPostHeaderAuthor(String postHeaderAuthor) {
        this.postHeaderAuthor = postHeaderAuthor;
    }
    public String getPostFolder() {
        return this.postFolder;
    }
    
    public void setPostFolder(String postFolder) {
        this.postFolder = postFolder;
    }




}


