package model.entidad;
// Generated 28-ene-2016 20:10:08 by Hibernate Tools 4.3.1



/**
 * CgAreaStore generated by hbm2java
 */
public class CgAreaStore  implements java.io.Serializable {


     private Integer areaStoreId;
     private String areaStoreName;

    public CgAreaStore() {
    }

    public CgAreaStore(String areaStoreName) {
       this.areaStoreName = areaStoreName;
    }
   
    public Integer getAreaStoreId() {
        return this.areaStoreId;
    }
    
    public void setAreaStoreId(Integer areaStoreId) {
        this.areaStoreId = areaStoreId;
    }
    public String getAreaStoreName() {
        return this.areaStoreName;
    }
    
    public void setAreaStoreName(String areaStoreName) {
        this.areaStoreName = areaStoreName;
    }




}


